name: Get Swimming Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v3

    - name: Clone the private repository
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git clone https://$PERSONAL_ACCESS_TOKEN@github.com/uwaggs/swimming.git

    - name: release - swimming_team_rankings
      id: team_release
      uses: softprops/action-gh-release@v2
      with:
        files: swimming/swimming_team_rankings.csv
        tag_name: swimming_team_rankings
        token: ${{ secrets.GH_TOKEN }}

    - name: release - swimming_athlete_rankings
      id: athlete_release
      uses: softprops/action-gh-release@v2
      with:
        files: swimming/swimming_athlete_rankings.csv
        tag_name: swimming_athlete_rankings
        token: ${{ secrets.GH_TOKEN }}
