
name: Get Swimming Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v3

    - name: Clone the private repository
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git clone https://$PERSONAL_ACCESS_TOKEN@github.com/uwaggs/swimming.git

    - name: swimming
      id: swimming
      uses: softprops/action-gh-release@v2
      with:
        files: |
          swimming/swimming_team_rankings.csv
          swimming/swimming_athlete_rankings.csv
        tag_name: swimming
        token: ${{ secrets.GH_TOKEN }}

